### ISSUE TITLE
Error 500: TypeInfo.as_dict() got an unexpected keyword argument 'search_users_supported'

### ISSUE THREAD

**Issue by edantie** [VirtualCable/openuds#110]
I'm trying openuds, but got error on opening authenticators:
Error handling your request
Error 500: TypeInfo.as_dict() got an unexpected keyword argument 'search_users_supported'

Master version of openUDS
Working with python 3.12.1 on Ubuntu 22.04.

[uds_error.txt](https://github.com/VirtualCable/openuds/files/14401340/uds_error.txt)

**Comment by dkmstr** [comment]
Master version is not usable in any way currently. I'm doing a massive refactoring, type checking, etc... :)

Only "Stables" versions are usable, as the Readme.md notes says.

Anyway, once this has ben said, thanks for your report... It's effectively a missinclusion of type data on the rerents modifications :)

Thank you!!

**Comment by edantie** [comment]
I know it's not for production, but a having a look to what's coming is one of my defects... too curious. Happy it has helped a little.

**Comment by dkmstr** [comment]
You helped more than you think. I remade that part of code, to be more "error prone" in the future...
Snoop around all you want, any report is welcome (an needed), especially with the enormous amount of code changes I'm making... ;-)

Again, regards
